version: "3.3"
networks:
  covid:
    driver: bridge

services:
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka-container
    depends_on:
      - zookeeper
    ports:
      - 9093:29092 # if you are changing port, change: - spring.kafka.consumer.bootstrap-servers=kafka:<new-port> - spring.kafka.producer.bootstrap-servers=kafka:<new-port>
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - covid

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper-container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2182:2181 
    networks:
      - covid


  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui-container
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    ports:
      - "9090:8080"
    depends_on:
      - kafka
    networks:
      - covid
        
  mysqldb:
    image: mysql:8.0.36
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: dockerDB
    networks:
      - covid

  eureka-server:
    image: ganesaselva/eureka-server:latest
    container_name: eureka-container
    build:
      context: eureka
      dockerfile: dockerfile
    ports:
      - "8761:8761"  # if you are changing port, change env: - eureka.client.service-url.defaultZone=http://eureka-server:<<new-port>/eureka
    networks:
      - covid

  config-server:
    image: ganesaselva/configservice:latest
    container_name: config-container
    build:
      context: configservice
      dockerfile: dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    ports:
      - "8888:8888" # if you are changing port, change env: - spring.config.import=optional:configserver:http://config-server:<new-port>/
    networks:
      - covid
    links:
      - eureka-server

  authentication-service:
    image: ganesaselva/authentication-service:latest
    container_name: authentication-container
    build:
      context: authentication
      dockerfile: dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/dockerDB?createDatabaseIfNotExist=true&user=root&password=root1234
      - spring.kafka.consumer.bootstrap-servers=kafka:9093
    ports:
      - "8082:8082" # if you are changing port in change env for swagger-server - springdoc.swagger-ui.urls[0].url=http://localhost:<new-port>/v3/api-docs
    networks:
      - covid
    depends_on:
      - mysqldb
      - config-server
    links:
      - eureka-server
      - config-server
      - mysqldb
      - zookeeper
      - kafka
    restart: on-failure
    entrypoint: sh -c "apk --no-cache add curl && /bin/sh -c 'until curl -sSf http://config-server:8888/actuator/health; do echo \"Waiting for config-server to be healthy...\"; sleep 5; done' && java -jar /usr/src/authentication-0.0.1-SNAPSHOT.jar"

  userprofile-service:
    image: ganesaselva/userprofile-service:latest
    container_name: userprofile-container
    build:
      context: userprofile
      dockerfile: dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/dockerDB?createDatabaseIfNotExist=true&user=root&password=root1234
      - spring.kafka.producer.bootstrap-servers=kafka:9093
    ports:
      - "8081:8081" # if you are changing port in change env for swagger-server - springdoc.swagger-ui.urls[1].url=http://localhost:<new-port>/v3/api-docs    
    networks:
      - covid
    depends_on:
      - mysqldb
      - config-server
    links:
      - eureka-server
      - config-server
      - mysqldb
      - zookeeper
      - kafka
    restart: on-failure
    entrypoint: sh -c "apk --no-cache add curl && /bin/sh -c 'until curl -sSf http://config-server:8888/actuator/health; do echo \"Waiting for config-server to be healthy...\"; sleep 5; done' && java -jar /usr/src/userprofile-0.0.1-SNAPSHOT.jar"

  covid-service:
    image: ganesaselva/covidservice:latest
    container_name: covid-container
    build:
      context: covid
      dockerfile: dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
    ports:
      - "8083:8083" # if you are changing port in change env for swagger-server - springdoc.swagger-ui.urls[2].url=http://localhost:<new-port>/v3/api-docs
    networks:
      - covid
    depends_on:
      - config-server
    links:
      - eureka-server
      - config-server
    restart: on-failure
    entrypoint: sh -c "apk --no-cache add curl && /bin/sh -c 'until curl -sSf http://config-server:8888/actuator/health; do echo \"Waiting for config-server to be healthy...\"; sleep 5; done' && java -jar /usr/src/covid-0.0.1-SNAPSHOT.jar"

  bookmark-service:
    image: ganesaselva/bookmark-service:latest
    container_name: bookmark-container
    build:
      context: bookmarkservice
      dockerfile: dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/dockerDB?createDatabaseIfNotExist=true&user=root&password=root1234
    ports:
      - "8084:8084" # if you are changing port in change env for swagger-server - springdoc.swagger-ui.urls[3].url=http://localhost:<new-port>/v3/api-docs
    networks:
      - covid
    depends_on:
      - config-server
      - mysqldb
    links:
      - eureka-server
      - config-server
      - mysqldb
    restart: on-failure
    entrypoint: sh -c "apk --no-cache add curl && /bin/sh -c 'until curl -sSf http://config-server:8888/actuator/health; do echo \"Waiting for config-server to be healthy...\"; sleep 5; done' && java -jar /usr/src/bookmarkservice-0.0.1-SNAPSHOT.jar"

  api-gateway:
    image: ganesaselva/gatewayservice:latest
    container_name: gateway-container
    build:
      context: gateway
      dockerfile: dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
    ports:
      - "9091:9091"
    networks:
      - covid
    depends_on:
      - config-server
    links:
      - eureka-server
      - config-server
    restart: on-failure
    entrypoint: sh -c "apk --no-cache add curl && /bin/sh -c 'until curl -sSf http://config-server:8888/actuator/health; do echo \"Waiting for config-server to be healthy...\"; sleep 5; done' && java -jar /usr/src/gateway-0.0.1-SNAPSHOT.jar"

  covid-app:
    image: ganesaselva/covid:latest
    build:
      context: ../CovidFECaseStudy/covid
      dockerfile: Dockerfile
    container_name: covid-app-angular
    ports:
      - "4201:4201" # sorry you can't change port for this due to page reload configuration by nginx
    networks:
      - covid